---
name: kosmic-new-year
on:
  push:
  pull_request:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install python-twitter

      - name: Build site
        run: python3 kosmic.py
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}

      - name: Update cached data
        run: |
          git config --global user.name 'Automatic Update'
          git config --global user.email relrod@users.noreply.github.com'
          git add .
          git commit -sm 'Latest tweet'
          git push

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: .
